# Generated by Django 2.2.5 on 2019-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190918_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Homepage'),
        ),
        migrations.AddField(
            model_name='pages',
            name='meta_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Description (meta)'),
        ),
        migrations.AddField(
            model_name='pages',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (meta)'),
        ),
    ]
