# Generated by Django 2.2.5 on 2019-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190918_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Homepage?'),
        ),
    ]
