# Generated by Django 2.2.5 on 2019-09-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190918_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'Pages'},
        ),
    ]
